# Generated by Django 4.2.2 on 2023-06-28 14:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogconts',
            fields=[
                ('Blog_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Blog_name', models.CharField(max_length=150)),
                ('Blog_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Author_name', models.CharField(max_length=30)),
                ('Blog_content', ckeditor.fields.RichTextField(default='about blog content')),
                ('stars', models.IntegerField(default=3)),
            ],
        ),
        migrations.DeleteModel(
            name='blogcont',
        ),
    ]
