# Generated by Django 4.2.2 on 2023-06-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blogconts_delete_blogcont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogconts',
            old_name='Blog_image',
            new_name='photo_image',
        ),
    ]
