# Generated by Django 4.2.2 on 2023-06-29 04:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0003_rename_blog_image_blogconts_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogcont',
            fields=[
                ('Blog_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Blog_name', models.CharField(max_length=150)),
                ('photo_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Blog_content', ckeditor.fields.RichTextField(default='about blog content')),
                ('stars', models.IntegerField(default=3)),
                ('Author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='blogconts',
        ),
    ]
